# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cc8af201978189f3278389de5f4c605fab147ab978b3887c3e1ae130a3537eac3daebb2ccf3e414ed1edd34ebb25351f1ed598a2e1e8a5d9356d3a89e8a2d33
  mobile_api:
    psms_info_url: https://api.fortumo.com/api/services/2/service.information.xml
    secret:        XXX
  cross_platform_api:
    service_id:    some-kind-of-uuid
    secret:        YYY

test:
  secret_key_base: 5fa35bc6a16b0bd700ff0825361ad6e7d96b92d0cccb5043a3d6ef4957e8bbeac6b01abe663ed06fc146d5a6f2fbbcfcbb6362be72c2b521936661f72b90f08c
  mobile_api:
    psms_info_url: https://api.fortumo.com/api/services/2/service.information.xml
    secret:        XXX
  cross_platform_api:
    service_id:    some-kind-of-uuid
    secret:        YYY

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  mobile_api:
    psms_info_url: <%= ENV['MOBILE_API_PSMS_INFO_URL'] %>
    secret:        <%= ENV['MOBILE_API_SECRET'] %>
  cross_platform_api:
    service_id: <%= ENV['CROSS_PLATFORM_API_SERVICE_ID'] %>
    secret:     <%= ENV['CROSS_PLATFORM_API_SECRET'] %>
